#include <iostream.h>
#include <conio.h>
void main(){
clrscr();
 cout<<"\n================charecter set============================\n";
 cout<<"Letter | Digits | special charecters | white space";
 cout<<"\n================Basic data types==========================\n";
 cout<<"char | int | short int | logn int | float | double |long double";
 cout<<"\n================Tokens====================================\n";
 cout<<"Keywords | Identifiers | Literals | Punctuators | Operators";

 getch();
}


