#include <iostream.h>
#include <stdio.h>
#include <conio.h>

void main(){
clrscr();  // any printed on screen all the clear this
 // define function, list library function, call function, inline function;
 // function is a blocks of code that perform a task to accomplish productive.
 // there is two type of function user defind function or library function.
 // use : first include in header using "# <library name.h>"
 char x[100];
 gets(x);
 puts(x);

getche();
}