//=================Introduction to C++ ====================================
// Funder bjarne stroustrup
// Developments at AT&T Bell laboratories in early 1980s
// first object oriented programming language(OOP)
// charector set, token, basic data types
// utility of defferent types of operators , input /output and structure.
//======================== Start ========================================


#include <iostream.h>
#include <conio.h>
void main(){
clrscr();
 cout<<"\n================charecter set============================\n";

 cout<<"Letter | Digits | special charecters | white space";

 cout<<"\n================Basic data types==========================\n";

 cout<<"char | int | short int | logn int | float | double |long double";
 //==========================================================================
 cout<<"char | sizeof | order of precedence | type of conversion (implicit, explicit) | constent | veriable |input/output";

 cout<<"\n================Tokens====================================\n";

 cout<<"Keywords | Identifiers | Literals | Punctuators | Operators";

 getch();
}
